### ISSUE TITLE
Obsidian crashes on wayland when changing vault.

### ISSUE THREAD

**Issue by antoKeinanen** [flathub/md.obsidian.Obsidian#212]
### Description

If you are on Wayland and have `--env=OBSIDIAN_USE_WAYLAND=1` enabled. When changing vaults Obsidian crashes.

### System Information

```bash session
Os: Fedora Linux 38 (Workstation Edition) x86_64
De: Gnome 44.5
Flatpak: 1.15.4
Obsidian: 1.4.14
GPU: Nvidia RTX 3070
NVRM version: NVIDIA UNIX x86_64 Kernel Module  535.113.01  Tue Sep 12 19:41:24 UTC 2023
GCC version:  gcc version 13.2.1 20230728 (Red Hat 13.2.1-1) (GCC)
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;xdg-run/gnupg:ro;/mnt;/run/media;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
OBSIDIAN_USE_WAYLAND=1
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
OBSIDIAN_DISABLE_GPU_SANDBOX=0
```

### Logs

```bash session
Debug: Will run Obsidian with the following arguments: --ozone-platform=wayland --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations
Debug: Additionally, user gave:
[13:1004/171734.733813:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-10-04 14:17:34 Loading main app package /app/resources/obsidian.asar
LaunchProcess: failed to execvp:
xdg-settings
[13:1004/171734.867022:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:1004/171734.867062:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-10-04 14:17:34 Checking for update using Github
2023-10-04 14:17:34 Success.
2023-10-04 14:17:34 Latest version is 1.4.14
2023-10-04 14:17:34 App is up to date.
[64:1004/171734.951153:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[64:1004/171734.951231:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[64:1004/171734.951332:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[64:1004/171734.951376:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[64:1004/171734.951411:ERROR:shared_image_factory.cc(673)] CreateSharedImage: could not create backing.
[64:1004/171734.951448:ERROR:shared_image_factory.cc(527)] DestroySharedImage: Could not find shared image mailbox
[64:1004/171734.951508:ERROR:gpu_service_impl.cc(1010)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[13:1004/171734.956427:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=8704
[73:1004/171734.963064:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[99:1004/171735.027846:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[99:1004/171735.027920:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[99:1004/171735.028022:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[99:1004/171735.028082:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[99:1004/171735.028118:ERROR:shared_image_factory.cc(673)] CreateSharedImage: could not create backing.
[99:1004/171735.028155:ERROR:shared_image_factory.cc(527)] DestroySharedImage: Could not find shared image mailbox
[99:1004/171735.028226:ERROR:gpu_service_impl.cc(1010)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[73:1004/171735.031062:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[13:1004/171735.033329:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=8704
[113:1004/171735.104888:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[113:1004/171735.104968:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[113:1004/171735.105070:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[113:1004/171735.105113:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[113:1004/171735.105146:ERROR:shared_image_factory.cc(673)] CreateSharedImage: could not create backing.
[113:1004/171735.105192:ERROR:shared_image_factory.cc(527)] DestroySharedImage: Could not find shared image mailbox
[113:1004/171735.105261:ERROR:gpu_service_impl.cc(1010)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[13:1004/171735.110450:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=8704
[73:1004/171735.125095:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
/app/bin/obsidian.sh: line 41:    13 Segmentation fault      (core dumped) zypak-wrapper /app/obsidian $@ ${EXTRA_ARGS[@]}
```
```

**Comment by joshua-stone** [comment]
Does this happen in XWayland or Xorg?

Does it happen when forcing Wayland with the other builds? Make sure you're running the following:
```
$ ./obsidian --ozone-platform=wayland --ozone-platform-hint=auto  --enable-features=UseOzonePlatform,WaylandWindowDecorations
```

**Comment by antoKeinanen** [comment]
Yes, it also happens when using the AppImage. So it's not probably the flatpack that's the issue.
```
$ ./obsidian --ozone-platform=wayland --ozone-platform-hint=auto  --enable-features=UseOzonePlatform,WaylandWindowDecorations
```
Logs:
```
2023-10-05 05:29:35 Loading main app package /tmp/.mount_ObsidiEzH1aQ/resources/obsidian.asar
Error: ENOENT: no such file or directory, open '/home/akk/.config/obsidian/obsidian.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at Object.readFileSync (node:fs:469:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9212)
    at /tmp/.mount_ObsidiEzH1aQ/resources/obsidian.asar/main.js:1:3390
    at R (/tmp/.mount_ObsidiEzH1aQ/resources/obsidian.asar/main.js:1:2117)
    at E (/tmp/.mount_ObsidiEzH1aQ/resources/obsidian.asar/main.js:1:3371)
    at module.exports (/tmp/.mount_ObsidiEzH1aQ/resources/obsidian.asar/main.js:6:3411)
    at loadApp (/tmp/.mount_ObsidiEzH1aQ/resources/app.asar/main.js:294:3)
    at Object.<anonymous> (/tmp/.mount_ObsidiEzH1aQ/resources/app.asar/main.js:446:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/akk/.config/obsidian/obsidian.json'
}
2023-10-05 05:29:36 Checking for update using Github
2023-10-05 05:29:36 Success.
2023-10-05 05:29:36 Latest version is 1.4.14
2023-10-05 05:29:36 App is up to date.
[5511:1005/082936.368762:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[5511:1005/082936.368880:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[5511:1005/082936.369008:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[5511:1005/082936.369062:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[5511:1005/082936.369110:ERROR:shared_image_factory.cc(673)] CreateSharedImage: could not create backing.
[5511:1005/082936.369158:ERROR:shared_image_factory.cc(527)] DestroySharedImage: Could not find shared image mailbox
[5511:1005/082936.369215:ERROR:gpu_service_impl.cc(1010)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5460:1005/082936.375930:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=8704
[5546:1005/082936.524109:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[5546:1005/082936.524187:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[5546:1005/082936.524308:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[5546:1005/082936.524353:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[5546:1005/082936.524390:ERROR:shared_image_factory.cc(673)] CreateSharedImage: could not create backing.
[5546:1005/082936.524429:ERROR:shared_image_factory.cc(527)] DestroySharedImage: Could not find shared image mailbox
[5546:1005/082936.524482:ERROR:gpu_service_impl.cc(1010)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5460:1005/082936.530957:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=8704
[5556:1005/082936.669928:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[5556:1005/082936.670004:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[5556:1005/082936.670123:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[5556:1005/082936.670169:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[5556:1005/082936.670206:ERROR:shared_image_factory.cc(673)] CreateSharedImage: could not create backing.
[5556:1005/082936.670245:ERROR:shared_image_factory.cc(527)] DestroySharedImage: Could not find shared image mailbox
[5556:1005/082936.670298:ERROR:gpu_service_impl.cc(1010)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5460:1005/082936.677482:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=8704
```

**Comment by joshua-stone** [comment]
Thanks for following-up. [Please file a bug with the upstream issue tracker](https://forum.obsidian.md/tags/c/bug-reports/7/linux).

**Comment by hworld** [comment]
Wanted to put this here in case anyone encounters. It seems that under Wayland for me (Fedora/Gnome) it was crashing when there were two windows open (which is what happens when you open a new vault).

I was able to fix it by switching the "Window frame style" to "Native frame". It's a bit annoying since now the window takes up more height, but at least I can open multiple windows now.

![image](https://github.com/flathub/md.obsidian.Obsidian/assets/1024321/4cbb4c70-8007-4728-a012-1ebd7e83f1b8)

Hope this helps someone else.

**Comment by omnigenous** [comment]
@hworld Since I can't open obsidian on desktop is there a way to change this setting on mobile? I got syncing set up.

**Comment by omnigenous** [comment]
@antoKeinanen Did you manage to fix this? I got exact same issue and can't find a fix.

**Comment by antoKeinanen** [comment]
Well yes and no. I didn't get it to work on wayland so I switched to X11 and it works as expected.
