### ISSUE TITLE
default wayland or x11 icon is shown instaead of the icon

### ISSUE THREAD

**Issue by Wladefant** [flathub/md.obsidian.Obsidian#265]
### Description

![image](https://github.com/flathub/net.cozic.joplin_desktop/assets/79611093/f0df4e3d-0a05-41fe-9c75-877fbcc32f1a) Just to be clear the same happens with x11 just with a x11 icon

Here is how to fix this: https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/

### Obsidian Version

```bash session
Obsidian - Markdown-based knowledge base

          ID: md.obsidian.Obsidian
         Ref: app/md.obsidian.Obsidian/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.4.16
     License: LicenseRef-proprietary=https://obsidian.md/eula
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 586.4 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 766fe74388ac8115b7d6f4f2c2495f34bf5bba27017120ff3d3e1d9aa6c59a6c
      Parent: 998272fadebfea1fc18af767ef3d6c41a565a145401e00943b118502afc3d7ed
     Subject: Update git-2.42.1.tar.xz to 2.43.0 (c513b382)
        Date: 2023-11-20 18:52:14 +0000
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;xdg-run/gnupg:ro;/mnt;/run/media;~/.local/share/fonts:ro;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_CLEAN_CACHE=1
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
```

### Hardware Information

```bash session
Operating System: Fedora Linux 39
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.5.12-300.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i7-11850H @ 2.50GHz
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Dell Inc.
Product Name: Latitude 5521
```

### Logs
```
wladefant@wladefant-dell-laptop:~$ flatpak run md.obsidian.Obsidian
Deleting cache directory: /home/wladefant/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
[14:1124/195126.470056:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-11-24 18:51:26 Loading main app package /app/resources/obsidian.asar
Error: ENOENT: no such file or directory, open '/home/wladefant/.var/app/md.obsidian.Obsidian/config/obsidian/obsidian.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at Object.readFileSync (node:fs:469:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9212)
    at /app/resources/obsidian.asar/main.js:1:3390
    at R (/app/resources/obsidian.asar/main.js:1:2117)
    at E (/app/resources/obsidian.asar/main.js:1:3371)
    at module.exports (/app/resources/obsidian.asar/main.js:6:3411)
    at loadApp (/app/resources/app.asar/main.js:294:3)
    at Object.<anonymous> (/app/resources/app.asar/main.js:446:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/wladefant/.var/app/md.obsidian.Obsidian/config/obsidian/obsidian.json'
}
LaunchProcess: failed to execvp:
xdg-settings
[14:1124/195126.571831:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[14:1124/195126.571853:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-11-24 18:51:26 Checking for update using Github
2023-11-24 18:51:26 Success.
2023-11-24 18:51:26 Latest version is 1.4.16
2023-11-24 18:51:26 App is up to date.
[57:1124/195130.614410:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!

```

**Comment by joshua-stone** [comment]
@Wladefant Have you tested this with other builds? I'm not sure the fix linked is relevant because flatpak is generally strict about ensuring application files have matching names:

```
$ flatpak run --command=find md.obsidian.Obsidian /app -name 'md.obsidian.Obsidian.*'
/app/share/app-info/icons/flatpak/128x128/md.obsidian.Obsidian.png
/app/share/app-info/icons/flatpak/64x64/md.obsidian.Obsidian.png
/app/share/app-info/xmls/md.obsidian.Obsidian.xml.gz
/app/share/appdata/md.obsidian.Obsidian.appdata.xml
/app/share/applications/md.obsidian.Obsidian.desktop
/app/share/icons/hicolor/512x512/apps/md.obsidian.Obsidian.png
```

**Comment by Wladefant** [comment]
No, that is my first install and thank you for the fast answer, will later report back with the info. And yes this fix does not apply for sure

**Comment by joshua-stone** [comment]
@Wladefant Does updating icons help? Here's how you'd do it in Fedora Workstation / Silverblue (not sure if the same commands exist in the KDE spin):

https://discussion.fedoraproject.org/t/fedora-36-silverblue-no-flatpak-icons/69950/2

**Comment by tdworz** [comment]
I'm having the same problem running this flatpak on KDE, in Debian 12.

**Comment by joshua-stone** [comment]
Marking as closed since the issue may be transient and likely resolved itself by now.
