### ISSUE TITLE
Wayland check is broken

### ISSUE THREAD

**Issue by YaLTeR** [flathub/md.obsidian.Obsidian#284]
### Description

Running with `-x` shows:
```
+ [[ -e /run/user/1000//run/flatpak/wayland-0 ]]
```

It seems my `WAYLAND_DISPLAY` inside Flatpak contains the full path:
```
└─ flatpak run --user --command=sh md.obsidian.Obsidian
[📦 md.obsidian.Obsidian ~]$ echo $WAYLAND_DISPLAY
/run/flatpak/wayland-0
```

Running `flatpak run --user md.obsidian.Obsidian --ozone-platform-hint=auto` manually works fine.

### Obsidian Version

```bash session
Obsidian - Markdown-based knowledge base

          ID: md.obsidian.Obsidian
         Ref: app/md.obsidian.Obsidian/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.5.3
     License: LicenseRef-proprietary=https://obsidian.md/eula
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 594,4 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 34682b98e86132f6d92b00240883b32aa5712b734945cb8a8bac039a579dd8ad
      Parent: 8c4f3f2f432a01962b50d70ba990f13a5617e568cbe37ca5ddffc30c9f591b31
     Subject: Update 2 modules (71dee98c)
        Date: 2024-01-16 19:53:15 +0000
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;xdg-run/gnupg:ro;/mnt;/run/media;~/.local/share/fonts:ro;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_CLEAN_CACHE=1
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
```

### Hardware Information

```bash session
┌ ~
└─ lspci -nn | grep -E 'VGA|Display'
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev cf)
36:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c8)
┌ ~
└─ glxinfo -B
Error: unable to open display
```
(I don't have Xwayland running)

### System Information

Fedora 39 Silverblue, a [Smithay](https://github.com/Smithay/smithay)-based Wayland compositor ([niri](https://github.com/YaLTeR/niri)), flatpak-1.15.6-1.fc39.x86_64

### Logs

```bash session
└─ flatpak run --user --command=sh md.obsidian.Obsidian -x /app/bin/obsidian.sh
+ set -oue pipefail
+ EXTRA_ARGS=()
+ add_argument OBSIDIAN_DISABLE_GPU --disable-gpu
+ declare -i OBSIDIAN_DISABLE_GPU=0
+ [[ 0 -eq 1 ]]
+ add_argument OBSIDIAN_ENABLE_AUTOSCROLL --enable-blink-features=MiddleClickAutoscroll
+ declare -i OBSIDIAN_ENABLE_AUTOSCROLL=0
+ [[ 0 -eq 1 ]]
+ [[ -e /run/user/1000//run/flatpak/wayland-0 ]]
+ [[ 1 -eq 1 ]]
+ CACHE_DIRECTORIES=("${XDG_CONFIG_HOME}/obsidian/GPUCache")
+ for CACHE_DIRECTORY in "${CACHE_DIRECTORIES[@]}"
+ [[ -d /var/home/yalter/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache ]]
+ echo 'Deleting cache directory: /var/home/yalter/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache'
Deleting cache directory: /var/home/yalter/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
+ rm -rf /var/home/yalter/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
+ echo 'Debug: Will run Obsidian with the following arguments: '
Debug: Will run Obsidian with the following arguments:
+ echo 'Debug: Additionally, user gave: '
Debug: Additionally, user gave:
+ export FLATPAK_ID=md.obsidian.Obsidian
+ FLATPAK_ID=md.obsidian.Obsidian
+ export TMPDIR=/run/user/1000/app/md.obsidian.Obsidian
+ TMPDIR=/run/user/1000/app/md.obsidian.Obsidian
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-0
+ ln -sf app/com.discordapp.Discord/discord-ipc-0 /run/user/1000/discord-ipc-0
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-1
+ ln -sf app/com.discordapp.Discord/discord-ipc-1 /run/user/1000/discord-ipc-1
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-2
+ ln -sf app/com.discordapp.Discord/discord-ipc-2 /run/user/1000/discord-ipc-2
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-3
+ ln -sf app/com.discordapp.Discord/discord-ipc-3 /run/user/1000/discord-ipc-3
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-4
+ ln -sf app/com.discordapp.Discord/discord-ipc-4 /run/user/1000/discord-ipc-4
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-5
+ ln -sf app/com.discordapp.Discord/discord-ipc-5 /run/user/1000/discord-ipc-5
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-6
+ ln -sf app/com.discordapp.Discord/discord-ipc-6 /run/user/1000/discord-ipc-6
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-7
+ ln -sf app/com.discordapp.Discord/discord-ipc-7 /run/user/1000/discord-ipc-7
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-8
+ ln -sf app/com.discordapp.Discord/discord-ipc-8 /run/user/1000/discord-ipc-8
+ for i in {0..9}
+ test -S /run/user/1000/discord-ipc-9
+ ln -sf app/com.discordapp.Discord/discord-ipc-9 /run/user/1000/discord-ipc-9
+ zypak-wrapper /app/obsidian
[14:0124/091856.510763:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2024-01-24 05:18:56 Loading main app package /app/resources/obsidian.asar
Error: ENOENT: no such file or directory, open '/var/home/yalter/.var/app/md.obsidian.Obsidian/config/obsidian/obsidian.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at Object.readFileSync (node:fs:469:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9212)
    at /app/resources/obsidian.asar/main.js:3:801
    at U (/app/resources/obsidian.asar/main.js:2:3373)
    at z (/app/resources/obsidian.asar/main.js:3:782)
    at module.exports (/app/resources/obsidian.asar/main.js:8:3756)
    at loadApp (/app/resources/app.asar/main.js:294:3)
    at Object.<anonymous> (/app/resources/app.asar/main.js:446:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/home/yalter/.var/app/md.obsidian.Obsidian/config/obsidian/obsidian.json'
}
LaunchProcess: failed to execvp:
xdg-settings
[14:0124/091856.663097:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[14:0124/091856.663106:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
/app/bin/obsidian.sh: line 62:    14 Aborted                 (core dumped) zypak-wrapper /app/obsidian $@ ${EXTRA_ARGS[@]}
```

**Comment by YaLTeR** [comment]
Thanks! Btw my compositor sets `WAYLAND_DISPLAY=wayland-1` so it's something that Flatpak itself is doing.

**Comment by YaLTeR** [comment]
Yeah it runs on Wayland out of the box now.

**Comment by joshua-stone** [comment]
Excellent! If it turns out that we also need to test for `WAYLAND_DISPLAY=wayland-1` then we can re-open this issue.
